### ISSUE TITLE
Bootstrap Spinner will mess up banner and footer

### ISSUE THREAD

**Issue by HallofFamer** [indigojs/bootstrap-spinner#4]
Well I use this for a page of my site and the site has fixed banner and footer position. However, bootstrap spinner messes up with banner and footer in this case, placing itself on top of the banner or footer, while I want it to hide below the banner or footer. 

This is a screenshot of how it looks like:
http://oi68.tinypic.com/54jgw4.jpg

So is there a way to fix this css problem with bootstrap spinner?

**Comment by sagikazarmark** [comment]
Well, this is weird. You could try playing with z-index: the higher an element has, the higher it is placed. However, I don't maintain this library anymore, there are many others which do things better.

**Comment by HallofFamer** [comment]
I see, I will try to play with the z-index and see if it fixes problem. And btw what do you mean by 'there are many others which do things better'?

**Comment by sagikazarmark** [comment]
There are other spinner libraries which do the same task better. By the time I wrote this, I couldn't find any, but since then there are newers.

**Comment by HallofFamer** [comment]
I see, so can you link me to the newer libraries that do the same thing as your library? Id appreciate this.

**Comment by sagikazarmark** [comment]
Sorry, I don't have any concrete one lately. Google is your friend :smile: Try them out
